export const CONSTANTS = {
  CANVAS_WIDTH: 800,
  CANVAS_HEIGHT: 600,
  PLAYER_SPEED: 3,
  ZOMBIE_SPEED: 1.5,
  ZOMBIE_HP: 5,
  BIG_ZOMBIE_SPEED: 0.8,
  BIG_ZOMBIE_HP: 30,
  ZOMBIE_DAMAGE: 10,
  PLAYER_MAX_HP: 100,
  ATTACK_INTERVAL: 500, // ms
  ZOMBIE_DAMAGE_INTERVAL: 500, // ms
  HEAL_DELAY: 5000, // ms
  HEAL_RATE: 5, // hp per second
  ITEM_SPAWN_INTERVAL: 10000, // ms
  ITEM_LIFETIME: 8000, // ms
};
